#!/usr/bin/env bash
# a script tha installs nginx on your web-01 server
sudo apt-get update -y
sudo apt-get -y install nginx
sudo chown -R $ubuntu:ubuntu /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
