#!/usr/bin/env bash
# Configure 404 page
./3-redirection
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i '30 i\ \terror_page 404 /404.html;\n' /etc/nginx/sites-enabled/default 
service nginx restart
