#!/usr/bin/env bash
# configuration
apt-get -y update
apt-get -y install nginx
hostname=$(cat /etc/hostname)
sudo sed -i "37 i\ \tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-enabled/default
service nginx restart
