#!/usr/bin/env bash
# Fixing the container so that Nginx is running as the nginx user
pkill apache2
chmod 755 /etc/nginx/nginx.conf
sed -i -e 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/*
sudo -u nginx nginx -c /etc/nginx/nginx.conf
